# Example config
# see https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/hello-world/app.yaml
runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  server_url: crystal-hunt.appspot.com